name: Check docs spelling
on: 
  pull_request:
    branches:
      - main

jobs:
  spell-check:
    name: runner / spell-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install cspell
        run: npm install -g cspell

      - name: Create cspell config
        run: |
          echo '{
            "version": "0.2",
            "language": "en",
            "files": ["**/*.md"],
            "ignorePaths": ["node_modules/**", "dist/**", "build/**"],
            "dictionaryDefinitions": [
              {
                "name": "percona-words",
                "path": "./.cspell/percona-words.txt",
                "description": "Percona specific words"
              }
            ],
            "dictionaries": ["percona-words"]
          }' > cspell.json

      - name: Run spell check and create report
        id: spell-check
        run: |
          mkdir -p reports
          cspell "**/*.md" --config cspell.json --report-only > reports/spell-check-report.txt || true
          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat reports/spell-check-report.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Upload spell check report
        uses: actions/upload-artifact@v3
        with:
          name: spell-check-report
          path: reports/spell-check-report.txt
          if-no-files-found: error

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const report = `${{ steps.spell-check.outputs.report }}`;
            const hasErrors = report.includes('Unknown word');
            
            if (hasErrors) {
              const comment = `## Spell Check Report 🔍\n\n` +
                `The following spelling issues were found:\n\n` +
                '```\n' +
                report +
                '```\n\n' +
                `Please review and fix these spelling issues.`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            } else {
              const comment = `## Spell Check Report ✅\n\n` +
                `No spelling issues were found.`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            } 